[env:esp32-cyd]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
lib_ldf_mode = deep+
board_build.partitions = huge_app.csv
lib_deps =
  bodmer/TFT_eSPI
  https://github.com/PaulStoffregen/XPT2046_Touchscreen.git
build_flags =
  -D USER_SETUP_LOADED
  -include User_Setup.h
